### ISSUE TITLE
Program always running

### ISSUE THREAD

**Issue by Stengell** [turtlecoin/android-pool-monitor#1]
love everything about this program except that i cannot close it on my LG V30.
Notifications will appear in the top bar in the android os(no matter what i select in the programs options) also if i clear programs in the task manager, they still appear.

I know that i can just tell the OS to ignore the program, but it shouldn't be running in the background when i don't want i to be there and i am trying to close it. Hope you can make some option that prevents the program from running constantly.

**Comment by Centurion20** [comment]
Dude, you join github and the first thing you do is start complaining about other peoples work. You actually un-edit Live in the Windows HOST file. Sheesh, because you admit you need it for skype? Do you know why Live is invasive? Think about the snowden leaks. Xbox Live, looking at you over your "Live camera!" NSA's "SID Today" Windows SID you tool-burger! Re: Hope you can make some option that prevents the program from running constantly. There are app's that can do that!

**Comment by RocksteadyTC** [comment]
@Centurion20 take your hands off your hips.
